// info.js - text shown in the side panel for each engine part.
// A spec value can be a function, so it updates live with the rpm.
import { S, fmt, gasTemp, rpmN } from '../config.js';

// Info card for each part (key = part name used by the 3D model)
export const INFO = {
  'block': { name: 'Cylinder block', tag: 'Structure',
    desc: 'The aluminium casting that holds everything together. Two banks of six cylinders sit at 90° to each other around one crankshaft, and every bore is surrounded by water jackets that carry heat away. Head studs clamp the cylinder heads down onto its deck.',
    specs: [['Layout', '90° V12 (2 × 6)'], ['Cylinder pitch', '100 mm'], ['Bore × stroke', '≈ 90 × 75.2 mm'], ['Displacement', '≈ 5.7 L (from model)'], ['Material', 'Aluminium alloy']] },
  'head-gasket': { name: 'Head gasket', tag: 'Sealing',
    desc: 'A thin multi-layer steel sheet clamped between block and head. It seals three things at once: combustion pressure well over 100 bar, the coolant passages and the oil galleries. Overheating is what usually kills one, letting coolant and oil mix or leak into a cylinder. (This part is drawn in by hand; the CAD file omitted it.)',
    specs: [['Type', 'Multi-layer steel (MLS)'], ['Seals', 'Combustion · coolant · oil'], ['Peak cylinder pressure', '> 100 bar'], ['Quantity', '2 (one per bank)'], ['Clamping', 'Head studs, torqued in sequence']] },
  'head': { name: 'Cylinder head', tag: 'Valvetrain',
    desc: 'Houses the valves, camshafts and the roof of each combustion chamber. The intake ports face the V and the exhaust ports face outward toward the manifolds. Two exhaust ports per cylinder are visible on the outer face.',
    specs: [['Valves', '48 (4 per cylinder)'], ['Camshafts', '4 · DOHC'], ['Camshaft speed', () => fmt(S.rpm / 2) + ' rpm'], ['Valve events / s (all)', () => fmt(S.rpm / 120 * 48)], ['Material', 'Aluminium alloy']] },
  'valve-cover': { name: 'Valve covers', tag: 'Valvetrain',
    desc: 'Finished in red crackle paint, the Ferrari trademark, these covers seal the top of each head and keep oil around the camshafts and valve gear.',
    specs: [['Covers', '2 (one per bank)'], ['Finish', 'Red crackle paint'], ['Underneath', 'Camshafts, valves, springs']] },
  'spark-plug': { name: 'Spark plugs', tag: 'Ignition',
    desc: 'One plug per cylinder sits in the centre of the combustion chamber. A pulse of tens of thousands of volts makes a spark jump the electrode gap at exactly the right crank angle to light the compressed air–fuel mixture.',
    specs: [['Quantity', '12 · one per cylinder'], ['Coil voltage', '≈ 30–40 kV'], ['Tip', 'Iridium / platinum'], ['Sparks / cylinder / s', () => fmt(S.rpm / 120, 1)], ['Total sparks / s', () => fmt(S.rpm / 120 * 12)]] },
  'valve': { name: 'Valves', tag: 'Valvetrain',
    desc: 'Four per cylinder: two intake valves let the fresh charge in, two exhaust valves let the burnt gas out. Each opens and closes once every two crankshaft turns, driven by the camshafts. (Drawn static in this model.)',
    specs: [['Quantity', '48'], ['Layout', '2 intake + 2 exhaust per cylinder'], ['Opening events / s (each)', () => fmt(S.rpm / 120, 1)]] },
  'valve-spring': { name: 'Valve springs & retainers', tag: 'Valvetrain',
    desc: 'Coil springs snap each valve shut against its seat. At high revs they have to control the valve within a fraction of a millisecond, which is why they are one of the limits on maximum engine speed.',
    specs: [['Springs', '48 (one per valve)'], ['Includes', 'Washers / spring plates']] },
  'camshaft': { name: 'Camshafts', tag: 'Valvetrain',
    desc: 'Four overhead camshafts, two per bank, whose lobes push the valves open. They turn at exactly half crankshaft speed because each valve only opens once per two-revolution cycle.',
    specs: [['Count', '4 (DOHC, 2 per bank)'], ['Speed', () => fmt(S.rpm / 2) + ' rpm'], ['Ratio to crank', '1 : 2']] },
  'cam-caps': { name: 'Camshaft bearing caps', tag: 'Valvetrain',
    desc: 'Aluminium caps bolted over each camshaft journal, holding the shafts in their bearings while allowing them to spin freely in an oil film.',
    specs: [['Caps', '12 + 4 end caps'], ['Fasteners', 'Cap-head screws']] },
  'crankshaft': { name: 'Crankshaft', tag: 'Rotating assembly',
    desc: 'Converts the up-and-down thrust of the pistons into rotation. It has six throws, and each throw carries two connecting rods, one from each bank. The counterweights cancel the vibration of the moving parts. (You can watch it turn in the cutaway view.)',
    specs: [['Throws', '6 (two rods each)'], ['Stroke', '75.2 mm'], ['Speed', () => fmt(S.rpm) + ' rpm'], ['Power pulses / s', () => fmt(S.rpm / 60 * 6)]] },
  'crank-caps': { name: 'Main bearing caps', tag: 'Structure',
    desc: 'Bolted under the block, these caps hold the crankshaft in its main bearings and take the full load of every combustion event.',
    specs: [['Count', '7'], ['Bearing', 'Plain shell, oil-fed']] },
  'piston': { name: 'Pistons & gudgeon pins', tag: 'Rotating assembly',
    desc: 'The pistons are pushed down by the burning mixture and drive the crank through the connecting rods. Each is attached with a hollow steel gudgeon pin. At redline a piston stops and reverses direction 300 times a second. Switch to the cutaway view to see them move.',
    specs: [['Quantity', '12'], ['Diameter', '≈ 90 mm'], ['Stroke', '75.2 mm'], ['Mean piston speed', () => fmt(2 * 0.0752 * S.rpm / 60, 1) + ' m/s'], ['Direction changes / s', () => fmt(S.rpm / 60 * 2 * 1)]] },
  'conrod': { name: 'Connecting rods', tag: 'Rotating assembly',
    desc: 'Forged steel links between each piston and the crankshaft. They swing as the crank turns while the piston moves in a straight line, so they carry huge tension and compression loads at high revs.',
    specs: [['Quantity', '12'], ['Length (centre to centre)', '≈ 137 mm'], ['Material', 'Forged steel']] },
  'timing-gears': { name: 'Timing gears', tag: 'Drive',
    desc: 'Gears at the front of the engine link the crankshaft to the four camshafts and keep them in perfect step, so valves open at the exact crank angle every time.',
    specs: [['Gears', '1 crank + 4 cam'], ['Cam : crank', '1 : 2'], ['Crank gear', () => fmt(S.rpm) + ' rpm']] },
  'oil-pan': { name: 'Crankcase & oil pan', tag: 'Lubrication',
    desc: 'The lower casting encloses the crankshaft and collects the oil that drains back from the engine. Ribs on it stiffen the bottom end.',
    specs: [['Material', 'Cast aluminium'], ['Holds', 'Crankshaft, oil sump']] },
  'plenum': { name: 'Intake plenum', tag: 'Air',
    desc: 'The large red air box on top of the V. It feeds all twelve intake runners and evens out pressure pulses so each cylinder draws the same amount of air.',
    specs: [['Outlets', '12 runners'], ['Air drawn (approx.)', () => fmt(5.7 * 0.95 * S.rpm / 2 / 1000, 1) + ' m³/min']] },
  'runners': { name: 'Intake runners / injection pipes', tag: 'Air & fuel',
    desc: 'Individually tuned tubes carry air from the plenum to each cylinder’s intake ports. Their length uses pressure waves to ram in extra air at particular engine speeds, and the fuel injectors are mounted on them.',
    specs: [['Count', '12'], ['Material', 'Cast aluminium']] },
  'throttle': { name: 'Throttle bodies', tag: 'Air',
    desc: 'Butterfly valves that meter the air entering the plenum, one at each end. Opening them wider lets in more air, and the engine adds fuel to match.',
    specs: [['Quantity', '2'], ['Idle speed', '≈ 800 rpm'], ['Opening', () => fmt(4 + rpmN() * 92) + ' %']] },
  'exhaust-primaries': { name: 'Exhaust manifold · primary pipes', tag: 'Exhaust',
    desc: 'One tube per cylinder carries burnt gas from the exhaust ports on the outside of each head. Gas leaves the port at close to 1,000 °C, so at high load the metal glows orange from the port outward. The blue and gold tint is heat oxidising the stainless steel. (Drawn in by hand; the CAD file had no exhaust.)',
    specs: [['Pipes', '12 (6 per bank)'], ['Material', 'Stainless / Inconel'], ['Gas temperature (est.)', () => fmt(gasTemp()) + ' °C'], ['Glow', () => fmt(S.heat * 100) + ' %']] },
  'exhaust-collector': { name: 'Exhaust collector', tag: 'Exhaust',
    desc: 'Merges each bank’s six primary pipes into a single outlet that runs back toward the catalysts and silencers. It sees the highest sustained temperatures and glows strongest toward the rear.',
    specs: [['Collectors', '2'], ['Outlet', 'Rear flange → catalysts'], ['Gas temperature (est.)', () => fmt(gasTemp()) + ' °C'], ['Glow', () => fmt(S.heat * 100) + ' %']] },
  'pulleys': { name: 'Accessory pulleys', tag: 'Drive',
    desc: 'Three belt pulleys at the front of the engine drive accessories such as the water pump and alternator.',
    specs: [['Quantity', '3'], ['Speed (approx.)', () => fmt(S.rpm * 2) + ' rpm']] },
  'head-studs': { name: 'Head studs & nuts', tag: 'Hardware',
    desc: 'Long steel studs screw into the block and clamp each head down through the gasket. Torquing them evenly, in sequence, is what keeps the head gasket sealed under enormous pressure.',
    specs: [['Studs', '28'], ['Nuts', '28']] },
  'fasteners': { name: 'Fasteners', tag: 'Hardware',
    desc: 'Screws, bolts and nuts that hold the block, bearing caps, sump and intake together.',
    specs: [['Count', '100+']] },
};

// Groups used to build the parts list in the side panel
export const GROUPS = [
  ['Engine core', ['block', 'head-gasket', 'head', 'valve-cover', 'oil-pan', 'crank-caps']],
  ['Rotating assembly', ['crankshaft', 'piston', 'conrod', 'timing-gears']],
  ['Valvetrain & ignition', ['valve', 'valve-spring', 'camshaft', 'cam-caps', 'spark-plug']],
  ['Air & fuel', ['plenum', 'runners', 'throttle']],
  ['Exhaust', ['exhaust-primaries', 'exhaust-collector']],
  ['Drive & hardware', ['pulleys', 'head-studs', 'fasteners']],
];
